[build]
builder = "nixpacks"
buildCommand = "cd backend && npm ci && npm run build"

[deploy]
startCommand = "cd backend && npx prisma migrate deploy && npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicy = "on_failure"
maxRetries = 3 