services:
  - type: web
    name: muffme-backend
    env: node
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "npm run start:prod"
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: JWT_EXPIRATION
        value: 15m
      - key: JWT_REFRESH_EXPIRATION
        value: "2592000"
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false 